= Pandas 라이브러리

* 데이터 분석의 80~90%는 데이터를 수집하고 정리하는 일이 차지함
* 10~20%가 알고리즘을 선택하고, 모델링 결과를 분석하여 데이터로 부터 유용한 정보를 산출하는 분석 프로세스
* Pandas 라이브러리는 데이터를 수집하고 정리하는데 최적화된 도구
* Python을 기반으로 하여 쉬운 사용
* 데이터 분석을 위한 여러 종류의 클래스와 다양한 내장 함수를 제공

---

Pandas는 쉽고 직관적인 관계형 또는 분류된 데이터로 작업할 수 있도록 설계된 빠르고 유연하며 표현이 풍부한 데이터 구조를 제공하는 Python 패키지입니다. Pandas 라이브러리는 Python에서 실제 데이터 분석을 수행하기 위한 고수준의 객체 형태를 제공합니다.

Pandas는 다음 종류의 데이터에 적합한 분석 패키지입니다.

* SQL 테이블 또는 Excel 스프레드 시트에서와 같이 이질적으로 유형이 지정된 열이있는 데이블 형식 데이터
* 정렬되고 정렬되지 않은 시계열 데이터
* 행 및 열 레이블이 포함 된 임의의 행렬 데이터
* 다른 형태의 관찰 / 통계 데이터 세트

Pandas의 두 가지 주요 데이터 구조인 Series(1차원) 및 DataFrame(2차원)은 재무, 통계, 사회 과학 및 다양한 엔지니어링 분야의 일반적인 사용 사례의 대부분을 처리합니다. R에서 제공하는 data.frame이 제공하는 모든 것을 제공합니다. 또한 Numpy를 기반으로 하여 다른 많은 타사 라이브러리와 잘 통합되도록 설계 되었습니다.

Pandas는 다음의 수행과정에 적합합니다.

* 부동 소수점 데이터뿐만 아니라 누락 된 데이터(NaN)를 손쉽게 처리
* DataFrame 및 상위 차원 개체에서 열을 삽입하고 삭제할 수 있다.
* 입력하고자 하는 내용을 레이블 세트에 이름으로 정렬하거나 사용자가 레이블을 무시하고 Series, DataFrame 등으로 자동으로 데이터를 계산에 사용할 수 있다
* 데이터를 집계 및 변환하기 위해 데이터 세트에 분할 적용 및 유연한 그룹 별 기능 가능
* 다른 Python 및 NumPy 데이터 구조의 비정형 색인 생성 데이터를 DataFrame 객체로 쉽게 변환 할 수 있음
* 지능형 레이블 기반 슬라이싱, 인덱싱 및 대용량 데이터 세트의 하위 집합 가능
* 직관적인 데이터 병합 및 결합 가능
* 데이터 세트의 유연한 재 형성 및 피벗 가능
* 축의 계층적 레이블링 가능
* 플랫 파일(CSV), Excel 파일, 데이터베이스 및 초고속 HDF5 형식의 저장 / 로드 데이터에서 데이터로드를 위한 견고한 IO 도구 포함
* 날짜 범위 생성 및 빈도 반환, 이동 창 통계, 이동 윈도우 선형 회귀, 날짜 이동 및 지연 사용 가능

데이터 과학자의 경우 데이터 작업은 일반적으로 데이터 정리, 분석 / 모델링 그리고 분석 결과를 플로팅 또는 표 형식으로 표시하기에 적합한 형식으로 구성합니다.