= 산술연산: Series

* Pandas 산술 연산은 내부적으로 3단계 프로세스를 거침
1. column/row 인덱스를 기준으로 모든 원소를 정렬
2. 동일한 위치에 있는 원소끼리 1:1 로 대응
3. 1:1 대응이 되는 원소끼리 연산을 처리 (대응되는 원소가 없으면 NaN 처리)

---

Pandas 산술 연산은 내부적으로 3단계 프로세스를 거칩니다. 처음으로 행/열 인덱스를 기준으로 모든 원소를 정렬합니다. 그 다음으로 동일한 위치에 있는 원소를 정렬하고, 동일한 위치에 있는 원소끼리 일대일로 대응시킵니다. 이때 대응되는 원소가 없으면 NaN으로 처리합니다.

== Series 산술 연산

Series의 각 원소에 대해 산술연산을 수행할 수 있습니다.

=== Series와 숫자의 산술연산

Series 객체에 어떤 숫자를 더하면 Series의 개별 원소에 각각의 숫자를 더하고 계산한 결과를 Series 객체로 return 합니다. 사칙 연산 모두 가능합니다. 인덱스에 연산 결과를 매칭하여 Series를 return 합니다.

* Series와 숫자:
+
_Series_object (+, -. / *) 숫자
+
[source, python]
----
james = pd.Series({'국어': 100, '영어': 80, '수학': 90})
----
+
----
국어    100
영어     80
수학     90
dtype: int64
----
+
[source, python]
----
percentage = james /200
----
+
----
국어    0.50
영어    0.40
수학    0.45
dtype: float64
----

=== Series와 Series

Series와 Series사이의 연산은 Series의 모든 인덱스에 대하여 같은 인덱스를 가진 원소끼리 계산합니다. 인덱스에 결과를 매칭하여 새 Series를 return 합니다.

* Series와 Series
+
[source, python]
----
jason = pd.Series({'수학': 100, '국어': 80, '영어': 90})
total = james + jason
----
+
----
국어    180
수학    190
영어    170
dtype: int64
----

연산이 가능하지 않은 원소는 산술연산을 수행할 수 없습니다.

[source, python]
----
titles = ['titanic','terminator','true lies']
result = titles + 10
----

----
titles = ['titanic','terminator','true lies']
result = titles + 10
----

== 존재하지 않는 값 연산

연산을 하는 두 Series 원소 개수가 다르거나, 크기가 같더라도 인덱스 값이 다를 수 있습니다. 어느 한쪽에만 인덱스가 존재하고, 다른 쪽에는 짝을 지을 수 있는 동일한 인덱스가 없는 경우 정상적으로 연산을 처리할 수 없어, 이런 경우 유효한 값이 존재하지 않는다는 의미를 같는 NaN으로 처리합니다.

동일한 인덱스가 연산에 참여하는 Series에 존재하여 연산 대상 값이 대응되더라도 어느 한 쪽의 데이터 값이 존재하지 않는다면 NaN이 됩니다.

[source, python]
----
james = pd.Series({'국어':100, '영어':80, '수학':90})
celine = pd.Series({'과학':80, '국어':90, '영어':100})
total = celine + james
----

----
과학      NaN
국어    190.0
수학      NaN
영어    180.0
dtype: float64
----

== 연산 메소드

Series객체의 add(), sub(), mul(), div() 메소드를 사용하여 각각 사칙연산을 수행할 수 있습니다.

[source, python]
----
james = pd.Series({'국어':100, '영어':80, '수학':90})
celine = pd.Series({'과학':80, '국어':90, '영어':100})
total = celine.add(james)
----

----
과학      NaN
국어    190.0
수학      NaN
영어    180.0
dtype: float64
----

연산 결과가 NaN인 경우, fill_value 옵션을 설정하여 적용할 수 있습니다. 아래 코드는 NaN인 값을 0으로 간주하고 연산을 수행합니다.

[source, python]
----
james = pd.Series({'국어':100, '영어':80, '수학':90})
celine = pd.Series({'과학':80, '국어':90, '영어':100})
total = celine.add(james, fill_value=0)
----

----
과학     80.0
국어    190.0
수학     90.0
영어    180.0
dtype: float64
----
