= 누락 데이터 확인

* DataFrame에는 값이 누락되는 경우가 많음
* 파일 형식을 변경하는 과정에서 파일이 누락되는 경우가 많음
* 누락된 데이터는 NaN(Not a Number)로 표시함
* 누락 데이터가 많아지면 데이터의 품질이 떨어지고, 알고리즘을 왜곡하는 현상이 일어남

---

Seaborn 패키지에서 제공하는 titanic 데이터셋을 확인해 봅시다.

[source, python]
----
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df_titanic = sns.load_dataset('titanic')
df_titanic.head()
----

[%header, cols=16]
|===
||survived|pclass|sex|age|sibsp|parch|fare|embarked|class|who|adult_male|deck|embark_town|alive|alone
|0|	0|	3|	male|	22.0|	1|	0|	7.2500|	S|	Third|	man|	True|	NaN|	Southampton|	no|	False
|1|	1|	1|	female|	38.0|	1|	0|	71.2833|C|	First|	woman|	False|	C|Cherbourg|	yes|	False
|2|	1|	3|	female|	26.0|	0|	0|	7.9250|	S|	Third|	woman|	False|	NaN|	Southampton|	yes|	True
|3|	1|	1|	female|	35.0|	1|	0|	53.1000|S|	First|	woman|	False|	C|	Southampton|	yes|	False
|4|	0|	3|	male|	35.0|	0|	0|	8.0500|	S|	Third|	man|	True|	NaN|	Southampton|	no|	True
|===

head() 메소드로 출력하면 'deck' 열에 값이 있습니다. 이 승객의 경우 몇 번 데크에 승선했는지 데이터가 없다는 뜻입니다.

info() 메소드로 DataFrame의 요약정보를 출락하면 각 열에 속하는 데이터에서 결측치를 제외한 값을 보여줍니다. 

[source, python]
----
df_titanic.info()
----

----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB
----

deck에 결측치가 많은 것을 알 수 있습니다. 결측치의 수는 시리즈 객체의 value_conunts() 메소드를 호출하여 알 수 있습니다. 결과에 결측치를 포함하기 위해서는 dropna 파라미터에 False값을 주어야 합니다.

[source, python]
----
df_titanic['deck'].value_counts(dropna=False)
----

----
deck
NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: count, dtype: int64
----

DataFrame의 특정 컬럼에서 누락 데이터의 개수를 구하려면 math 모듈의 isnan() 함수를 사용할 수 있습니다. 아래 코드는 타이타닉 데이터셋에서 age 컬럼의 결측치 개수를 파악합니다.

[source, python]
----
import math

nan_value = 0
for i in df_titanic['age']:
    if math.isnan(i):
        nan_value += 1

print(nan_value)
----

함수를 만들어 사용할 수도 있습니다.

[source, python]
----
def get_nan_value(a):
    nan_value = 0
    for i in df_titanic[a]:
        if math.isnan(i):
            nan_value += 1
    return nan_value
----

누락 데이터 개수를 파악하는 가장 좋은 방법은, isnull() 메소드와 notnull() 메소드를 사용하는 것입니다.

[source, python]
----
df_titanic.head().isnull()
----

DataFrame에 isnull 함수를 사용하면 NaN인 열에 대해 True로 표시합니다.

[%header, cols=16]
|===
||survived|pclass|sex|age|sibsp|parch|fare|embarked|class|who|adult_male|deck|embark_town|alive|alone
|0|False|False|False|False|False|False|False|False|False|False|False|True|False|False|False
|1|False|False|False|False|False|False|False|False|False|False|False|False|False|False|False
|2|False|False|False|False|False|False|False|False|False|False|False|True|False|False|False
|3|False|False|False|False|False|False|False|False|False|False|False|False|False|False|False
|4|False|False|False|False|False|False|False|False|False|False|False|True|False|False|False
|===

notnull 함수를 사용하면 반대로 NaN인 열을 False로 표시합니다.

[%header, cols=16]
|===
||survived|pclass|sex|age|sibsp|parch|fare|embarked|class|who|adult_male|deck|embark_town|alive|alone
|0|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True|	False|	True|	True|	True
|1|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True
|2|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True|	False|	True|	True|	True
|3|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True
|4|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True|	True|	False|	True|	True|	True
|===

DataFrame에 대해 isnull 함수를 사용하면 DataFrame의 전체 데이터셋에서 누락 데이터 수를 확인할 수 있습니다.

[source, python]
----
df_titanic.isnull().sum(axis=0)
----

----
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64
----