= Data 분석 개요

* 데이터 분석의 일반적인 단계
1. Ask Questions
2. Wrangle Data (gather, access, clean)
3. Perform DEA(Explortory Data Analysis)
4. Draw conclusions
5. Communicate your results

---

데이터 분석 프로세는 아래와 같이 5단계로 진행됩니다.

1. Ask Questions (문제 정의 단계) +
주어진 데이터를 기반으로 어떤 분석을 할 수 있을지 질문해보는 단계입니다.
2. Wrangle Data (gather, access, clean) - (데이터 수집 및 전처리 단계) +
데이터를 수집하고, 데이터에 접근하고, 데이터 전처리를 하는 단계입니다. 데이터를 수집할 수 있는 방법은 여러가지가 있습니다. 웹 상에서 파일을 다운로드하거나, API를 통해 받아오거나, 웹 크롤링(스크랩핑)을 통해 가져오거나, 사내 데이터베이스에 저장된 파일을 이용할 수 있습니다. 데이터 수집 후 다음 단계는 접근입니다. 여기서 흔히 전처리라고 불리는 작업들을 해야 합니다. null인 값, 타입이 맞지 않는 값, 중복된 값들이 흔하게 존재합니다. 필요없이 중복된 값들은 제거를 해야 하고, null 값들은 평균값으로 대체를 한다든지 하는 전처리 작업을 해야 합니다. 이런 전처리, 클리닝 작업이 가장 복잡합니다. 
3. Perform EDA(Exploratory Data Analaysis) - (데이터 모델링 단계) +
탐색적 데이터 분석이라 불리는 이 단계는 데이터를 통해 중요한 의미와 정보를 찾아내는 방법론입니다. 주로 시각화 그래프를 통해 이루어집니다. 시각화 그래프를 통해 중요한 의미와 정보, 인사이트를 발견해내는 작업을 의미하며, 이는 데이터 분석을 위한 철학이라고도 볼 수 있습니다. 어떤 데이터를 분석할 지, 데이터를 어떻게 바라볼 지, 어떻게 해석할 지 등의 마인드셋이 여기에 해당합니다.
4. Draw colcusions (or even make predictions) - (시각화 및 탐색 단계) +
분석을 통하여 결과를 도출하는 단계입니다. 이 단계에서는 통계도 필요합니다.
5. Communicate your results +
결과를 리포팅하는 단계입니다. 데이터 분석가에게는 데이터 분석도 중요하지만 도출된 결과를 타인이게 잘 전달하는 것, 보고서로 잘 정리하는 것도 중요합니다.

