= HTML 페이지의 Table

* Load
** HTML 웹 페이지에 있는 <table> 태그에서 표 형식의 데이터를 모두 찾아서 DataFrame 형식으로 변환
** Table 데이터는 각각 별도의 DataFrame으로 변환됨
+
[source, python]
----
boxoffices = pd.read_html('https://movie.datamotion.co.kr/Boxoffice')
df_boxoffice = boxoffices[1]
----

** Save
* DataFrame 객체를 Html 형식 파일로 저장
+
[source, python]
----
df_boxoffice.to_html('boxoffice.html')
----

---

== Load

DataFrame은 웹 페이지의 태그를 읽어서 2차원 배열(행렬) 형태로 저장할 수 있는 테이블 형태의 데이터를 DataFrame에 적재할 수 있는 기능을 제공합니다. read_html() 메소드를 사용할 수 있으며, read_html() 메소드를 사용하면 DataFrame이 들어있는 list를 return 하며, list에서 DataFrame을 로드할 수 있습니다.

가장 단순한 형태의 HTML 테이블 로드는 아래와 같습니다.

[source, python]
----
boxoffice = pd.read_html('https://movie.datamotion.co.kr/Boxoffice')
df_boxoffice = boxoffice[1]
----

to_html() 메소드의 옵션은 아래와 같습니다.

[%header, cols="1,1,4", width=100%]
|===
|옵션|기본값|설명
|buf|-|저장할 버퍼 입니다. None이면 문자열로 출력됩니다.
|columns|-|열을 지정합니다.
|col_space|-|열 너비를 지정합니다. 픽셀 단위 입니다.
|header / index|-|열/행 레이블의 출력 여부 입니다. False이면 출력하지 않습니다.
|na_rep|NaN|결측값의 표현 방식 입니다.
|formatters|-|포매터 함수를 통해 값의 포맷을 설정합니다. .format() 메서드도 사용 가능합니다.
|float_format|-|소수점 단위 자리수를 지정합니다. 기본은 마침표( . ) 입니다. sparsify : 각 행의 모든 다중 인덱스 키를 인쇄하려면 계층적 인덱스가 있는 DataFrame에 대해 False로 설정합니다.
|index_names|True|인덱스명을 출력할지를 정합니다.
|justify|-|정렬 방식을 지정합니다.
|maxrows|-|최대 출력할 줄 수를 지정합니다. 초과되는 줄은 ( ... )형태로 축약됩니다.
|maxcols|-|최대 출력할 열 수를 지정합니다. 초과되는 줄은 ( ... )형태로 축약됩니다.
|minrow|-|maxrows로인해 잘린 표현을 표시할 수 입니다.
|show_dimensions|False|출력된 html 객체 아래에 데이터 객체의 차원을 출력합니다.
|decimal|.|1000단위 구분기호로 인식되는 문자를 지정합니다.
|bold_rows|True|출력에서 행 레이블을 굵게할지 여부입니다. 기본은 True입니다.
|classes|-|결과 html의 table에 적용할 css 클래스를 지정합니다.
|escape|True|문자 <, > 및 &를 HTML 안전 시퀀스로 변환합니다. 즉 문자를 HTML 문법이 아닌 문자 그대로 출력합니다.
|notebook|False|생성된 HTML이 IPython Notebook용인지 여부입니다. 기본은 False입니다.
|border|-|테두리의 두께를 지정합니다.
|encoding|-|인코딩을 지정합니다.
|table_id|-|css의 table id를 설정합니다.
|render_links|False|url을 html 링크로 변환합니다.
|===

== Save

DataFrame을 HTML 테이블 형태로 저장합니다. 가장 기본적인 형태의 저장은 아래와 같습니다.

[source, python]
----
df.to_html('./data/student.html')
----

아래 데이터 프레임을 HTML로 변환하면,

[source, python]
----
df = pd.DataFrame([ 
    ['Celine', 'France', 90, 100, 100],
    ['James','UK', 80, 40, 30],
    ['Jason','USA',80, 40, 60],
    ['Hans','Germany', 60, 50, 90]],
    columns = ['name','nation','korean','english','math']
)

df.to_html('./data/student.html')
----

아래와 같은 파일이 만들어집니다.

[source, html]
----
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>name</th>
      <th>nation</th>
      <th>korean</th>
      <th>english</th>
      <th>math</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Celine</td>
      <td>France</td>
      <td>90</td>
      <td>100</td>
      <td>100</td>
    </tr>
    <tr>
      <th>1</th>
      <td>James</td>
      <td>UK</td>
      <td>80</td>
      <td>40</td>
      <td>30</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Jason</td>
      <td>USA</td>
      <td>80</td>
      <td>40</td>
      <td>60</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Hans</td>
      <td>Germany</td>
      <td>60</td>
      <td>50</td>
      <td>90</td>
    </tr>
  </tbody>
</table>
----

저장 옵션은 아래와 같습니다.

[%header, cols="1,4", width=100%]
|===
|옵션|설명
|buf|저장할 버퍼 입니다. None이면 문자열로 출력됩니다.
|columns|출력할 열을 지정합니다.
|col_space|열 너비를 지정합니다. 픽셀 단위 입니다.
|header / index|열/행 레이블의 출력 여부 입니다. False이면 출력하지 않습니다.
|na_rep|결측값의 표현 방식 입니다.
|formatters|포매터 함수를 통해 값의 포맷을 설정합니다. .format() 메서드도 사용 가능합니다.
|float_format|소수점 단위 자리수를 지정합니다. 기본은 마침표( . ) 입니다. sparsify : 각 행의 모든 다중 인덱스 키를 인쇄하려면 계층적 인덱스가 있는 DataFrame에 대해 False로 설정합니다.
|index_names|인덱스명을 출력할지를 정합니다.
|justify|정렬 방식을 지정합니다.
|maxrows|최대 출력할 줄 수를 지정합니다. 초과되는 줄은 ( ... )형태로 축약됩니다.
|maxcols|최대 출력할 열 수를 지정합니다. 초과되는 줄은 ( ... )형태로 축약됩니다.
|minrow|maxrows로인해 잘린 표현을 표시할 수 입니다.
|show_dimensions|출력된 html 객체 아래에 데이터 객체의 차원을 출력합니다.
|decimal|1000단위 구분기호로 인식되는 문자를 지정합니다.
|bold_rows|출력에서 행 레이블을 굵게할지 여부입니다. 기본은 True입니다.
|classes| 결과 html의 table에 적용할 css 클래스를 지정합니다.
|escape|문자 <, > 및 &를 HTML 안전 시퀀스로 변환합니다. 즉 문자를 HTML 문법이 아닌 문자 그대로 출력합니다.
|notebook|생성된 HTML이 IPython Notebook용인지 여부입니다. 기본은 False입니다.
|border|테두리의 두께를 지정합니다.
|encoding|인코딩을 지정합니다.
|table_id|css의 table id를 설정합니다.
|render_links|url을 html 링크로 변환합니다.
|===